# Dockerfile.ui
# Blueprint for building the Streamlit frontend service

FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY .streamlit .streamlit
COPY ./src .

# Command to run the Streamlit app
CMD ["streamlit", "run", "ui.py", "--server.port", "8501", "--server.address", "0.0.0.0", "--server.enableCORS", "false", "--server.headless", "true"]
